[package]
name = "host"
version = "0.1.0"
authors = ["Richard Feldman <oss@rtfeldman.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
roc_std = { path = "../../lang/roc_std" }

[workspace]
